#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := kws_mfcc_nn_streaming

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/components/esp_adf_min/min

include $(IDF_PATH)/make/project.mk

ifndef MAKE_RESTARTS
$(info IDF_VER is $(IDF_VER))
endif